import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { AiFillStar, AiOutlineMenu } from "react-icons/ai";
import { BsTelephoneFill } from "react-icons/bs";
import { MdMail } from "react-icons/md";
import { FaFacebookF } from "react-icons/fa";
import { BsTwitter, BsInstagram } from "react-icons/bs";

export default function Home() {
  const [showMenu, setShowMenu] = useState(false);
  const handlerMenu = () => setShowMenu(!showMenu);
  return (
    <>
      <Head>
        <title>Portafolio Ricardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-mybrown text-zinc-50 sticky top-0 z-10">
        <div className="max-w-6xl mx-auto p-4">
          <div className="flex justify-between">
            <div className="flex gap-4">
              <a href="#">LOGO</a>
              <nav
                className={`bg-mybrown p-4  fixed z-10  left-0 w-full top-16 transition duration-300  ease-in-out	  ${
                  showMenu ? "opacity-1  " : "opacity-0  "
                }   `}
              >
                <ul className="text-center ">
                  <li>
                    <a
                      onClick={showMenu ? handlerMenu : null}
                      className="block p-4"
                      href="#proyectos"
                    >
                      Proyectos
                    </a>
                  </li>
                  <li>
                    <a
                      onClick={showMenu ? handlerMenu : null}
                      className="block p-4"
                      href="#testimonios"
                    >
                      Testimonios
                    </a>
                  </li>
                  <li>
                    <a
                      onClick={showMenu ? handlerMenu : null}
                      className="block p-4"
                      href="#contacto"
                    >
                      Contacto
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
            <div
              onClick={handlerMenu}
              className="border p-2  rounded-lg lg:hidden"
            >
              <AiOutlineMenu />
            </div>
          </div>
        </div>
      </header>
      <main>
        <section className="bg-mybrown pt-4 pb-16  md:py-32" aria-label="Hero">
          <div className="max-w-6xl mx-auto px-4">
            <div className="md:flex gap-12">
              <div className="flex justify-center relative md:order-2 md:flex-1 ">
                <Image
                  src="/perfil.svg"
                  title="perfil"
                  alt="perfil"
                  width={624}
                  height={466}
                  priority
                />
              </div>
              <div className="flex flex-col gap-6 md:flex-1">
                <h1 className="text-6xl font-extrabold text-zinc-50 leading-snug">
                  ¡Hola a todos! Soy Ricardo Pérez
                </h1>
                <p className="text-2xl font-normal	text-zinc-300">
                  Developer que le encanta implementar diseños que inspiran y
                  atraen a las personas.
                </p>
                <button
                  aria-label="Ver mi trabajo"
                  className="bg-violet-600 text-zinc-50 h-12 rounded-md font-black md:w-48"
                >
                  VER MI TRABAJO
                </button>
              </div>
            </div>
          </div>
        </section>
        <section
          className="bg-mypinksoft py-16   md:py-32"
          aria-label="My projects"
          id="proyectos"
        >
          <div className="max-w-6xl mx-auto px-4">
            <p className="pb-6 text-myorange tracking-[.15em]">PORTAFOLIO</p>
            <h2 className="text-4xl	font-extrabold pb-6 text-mychocolate md:text-6xl">
              Proyectos recientes
            </h2>
            <div className="flex flex-col gap-8 items-center md:flex-wrap md:flex-row">
              <article className="w-full relative rounded-2xl overflow-hidden max-w-xs		">
                <figure className="flex">
                  <Image
                    src="/project-niko.webp"
                    width={448}
                    height={576}
                    title="project Niko"
                    alt="project Niko"
                    objectFit="cover"
                  />
                </figure>
                <div className="absolute top-0 h-full w-full bg-stone-900/50 flex items-end">
                  <h3 className="p-5 text-4xl font-extrabold text-zinc-50">
                    Niko
                  </h3>
                </div>
              </article>
              <article className="w-full relative rounded-2xl overflow-hidden max-w-xs		">
                <figure className="flex">
                  <Image
                    src="/project-amazonas.webp"
                    width={448}
                    height={576}
                    title="project Amazonas"
                    alt="project Amazonas"
                    objectFit="cover"
                  />
                </figure>
                <div className="absolute top-0 h-full w-full bg-stone-900/50 flex items-end">
                  <h3 className="p-5 text-4xl font-extrabold text-zinc-50">
                    Amazonas
                  </h3>
                </div>
              </article>
              <article className="w-full relative rounded-2xl overflow-hidden max-w-xs		">
                <figure className="flex">
                  <Image
                    src="/project-principe.webp"
                    width={448}
                    height={576}
                    title="project Principe"
                    alt="project Principe"
                    objectFit="cover"
                  />
                </figure>
                <div className="absolute top-0 h-full w-full bg-stone-900/50 flex items-end">
                  <h3 className="p-5 text-4xl font-extrabold text-zinc-50">
                    Príncipe fresco
                  </h3>
                </div>
              </article>
            </div>
          </div>
        </section>
        <section className="py-16  md:py-32" aria-label="About me">
          <div className="max-w-6xl mx-auto px-4">
            <div className="md:flex gap-4 items-center">
              <div className="flex md:flex-1">
                <Image
                  src="/notebook.webp"
                  title="Laptop"
                  alt="Laptop"
                  width={528}
                  height={500}
                  priority
                />
              </div>
              <div className="flex  flex-col gap-6 md:flex-1">
                <p className="text-base text-violet-400 tracking-[.15em]">
                  RICARDO PÉREZ
                </p>
                <h2 className="font-extrabold text-4xl text-mychocolate md:text-6xl ">
                  Desarrollador web profesional
                </h2>
                <p className="text-mysoftbrown text-xl leading-loose">
                  Una de las cosas que más disfruto de la programación, es el
                  poder darle vida a las ideas de los clientes a través de la
                  tecnología y a su vez crear servicios accesibles para todo
                  tipo de usuarios.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          className=" bg-mypinksoft pt-4 pb-16 md:py-32"
          aria-label="Testimonies"
          id="testimonios"
        >
          <div className="max-w-6xl mx-auto px-4">
            <p className="text-center text-violet-400 tracking-[.15em]">
              TESTIMONIOS
            </p>
            <h2 className="font-extrabold text-2xl text-center py-10 text-mychocolate md:text-6xl">
              Estos son algunos testimonios de los clientes con los cuales he
              trabajado.
            </h2>
            <div className="lg:flex ">
              <article className="  md:h-[29rem] flex flex-col gap-12  border p-6">
                <div className="flex gap-3">
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                </div>
                <p className="text-xl leading-loose text-mysoftbrown">
                  Tengo algunos años trabajando con Javascript y aún así aprendí
                  varias cosas importantes de Ricardo y como utiliza Javascript
                  en el día a día.
                </p>
                <div className="flex items-center gap-6 ">
                  <div className="rounded-full flex ">
                    <Image
                      src="/testimony-juan.webp"
                      width={80}
                      height={80}
                      title="Testimonio Juan"
                      alt="Testimonio Juan"
                    />
                  </div>
                  <p className="text-2xl	font-bold text-mychocolate	">
                    Juan Antonio
                  </p>
                </div>
              </article>
              <article className="  md:h-[29rem] flex flex-col gap-12 p-6 bg-white shadow-lg">
                <div className="flex gap-3">
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                </div>
                <p className="text-xl leading-loose text-mysoftbrown">
                  Tengo algunos años trabajando con Javascript y aún así aprendí
                  varias cosas importantes de Ricardo y como utiliza Javascript
                  en el día a día.
                </p>
                <div className="flex items-center gap-6 ">
                  <div className="rounded-full flex ">
                    <Image
                      src="/testimony-eleanor.webp"
                      width={80}
                      height={80}
                      title="Testimonio Eleanor"
                      alt="Testimonio Eleanor"
                    />
                  </div>
                  <p className="text-2xl	font-bold	text-mychocolate">
                    Eleanor Pena
                  </p>
                </div>
              </article>
              <article className="  md:h-[29rem] flex flex-col gap-12  border p-6">
                <div className="flex gap-3">
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                  <AiFillStar className="h-6 w-6 text-yellow-400" />
                </div>
                <p className="text-xl leading-loose text-mysoftbrown">
                  Tengo algunos años trabajando con Javascript y aún así aprendí
                  varias cosas importantes de Ricardo y como utiliza Javascript
                  en el día a día.
                </p>
                <div className="flex items-center gap-6 ">
                  <div className="rounded-full flex ">
                    <Image
                      src="/testimony-darlene.webp"
                      width={80}
                      height={80}
                      title="Testimonio Darlene"
                      alt="Testimonio Darlene"
                    />
                  </div>
                  <p className="text-2xl	font-bold	text-mychocolate">
                    Darlene Robertson
                  </p>
                </div>
              </article>
            </div>
          </div>
        </section>
        <section
          className="py-16  md:py-32"
          aria-label="Contacts"
          id="contacto"
        >
          <div className="max-w-6xl mx-auto px-4">
            <div className="flex flex-col gap-10 md:flex-row">
              <div className="flex flex-col gap-6 text-left   md:order-2 md:flex-1">
                <p className="text-base tracking-[.15em] text-myorange ">
                  CONTACTO
                </p>
                <h2 className="font-extrabold text-4xl md:text-5xl text-mychocolate">
                  Si tienes un nuevo proyecto en mente, no dudes en contactarme.
                </h2>
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 flex items-center justify-center text-white bg-red-400 rounded-full">
                    <BsTelephoneFill />
                  </div>
                  <p className="text-xl text-mychocolate font-semibold	">
                    +1 (234) 928-22-34
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 flex items-center justify-center text-white bg-red-400 rounded-full">
                    <MdMail />
                  </div>
                  <p className="text-xl text-mychocolate font-semibold	">
                    ricardo.perez@gmail.com
                  </p>
                </div>
              </div>
              <div className="bg-stone-900 p-7 md:p-12 rounded-md  md:flex-1">
                <h3 className="text-2xl font-bold	text-slate-50 pb-6">
                  Envía un mensaje con los detalles de tu proyecto
                </h3>
                <form className="flex flex-col gap-6">
                  <div className="flex flex-col gap-4">
                    <label
                      className="font-semibold	text-slate-50 "
                      htmlFor="name"
                    >
                      NOMBRE COMPLETO
                    </label>
                    <input
                      className="px-4 py-2 rounded"
                      id="name"
                      name="name"
                      type="text"
                      placeholder="Ingresa tu nombre"
                    />
                  </div>
                  <div className="flex flex-col gap-4">
                    <label
                      className="font-semibold	text-slate-50 "
                      htmlFor="mail"
                    >
                      CORREO ELECTRÓNICO
                    </label>
                    <input
                      className="px-4 py-2 rounded"
                      name="mail"
                      id="mail"
                      type="mail"
                      placeholder="Ingresa tu correo electrónico"
                    />
                  </div>
                  <div className="flex flex-col gap-4">
                    <label
                      className="font-semibold	text-slate-50 "
                      htmlFor="description"
                    >
                      DESCRIPTION
                    </label>
                    <textarea
                      className="px-4 py-2 rounded"
                      name="description"
                      id="description"
                      cols="30"
                      rows="5"
                      placeholder="Ingresa una breve descripción del proyecto que tienes en mente"
                    ></textarea>
                  </div>
                  <button className="bg-violet-600 text-slate-50 py-4  px-6 rounded-md font-bold md:w-48">
                    ENVIAR MENSAJE
                  </button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-zinc-900 py-10">
        <div className="max-w-6xl mx-auto px-4">
          <div className="flex flex-col justify-center items-center gap-2 md:flex-row md:justify-between">
            <p className="text-white text-2xl font-extrabold">LOGO</p>
            <div className="flex gap-2">
              <div className="w-12 h-12 flex items-center justify-center text-white bg-red-400 rounded-full">
                <FaFacebookF />
              </div>
              <div className="w-12 h-12 flex items-center justify-center text-white bg-red-400 rounded-full">
                <BsTwitter />
              </div>
              <div className="w-12 h-12 flex items-center justify-center text-white bg-red-400 rounded-full">
                <BsInstagram />
              </div>
            </div>
          </div>
          <hr className="my-6 block" />
          <p className="text-center text-white md:text-left">
            Ricardo Peréz © 2022. Todos los derechos recervados
          </p>
        </div>
      </footer>
    </>
  );
}
